### ISSUE TITLE
How to correctly stop audio player

### ISSUE THREAD

**Issue by adelburekovic** [delannoyk/AudioPlayer#139]
I have a dismissable view controller which has an instance of `AudioPlayer`. Before I dismiss the view controller I check if the song is playing and stop the audio player with the provided `stop()` method. 

Everytime I do that I get an error in the log below:
`ERROR: AVAudioSession.mm:646: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.`

I checked the code a little and discovered that the issue is with `setAudioSession(active: false)` line in the `stop()` method.

Also if I try to play the song again really quickly after stopping the previous player the song doesn't play correctly (player just stops after few seconds). This issue is probably connected with audio session deactivation.

I am basically wondering if I am stopping the player incorrectly? Should I use some other approach (Maybe have one player in singleton)? Thanks.

**Comment by danielmartinprieto** [comment]
Hi, @adelburekovic. This is really interesting. Could you share some code here or a small sample project that showcase the issue?

**Comment by adelburekovic** [comment]
@danielmartinprieto hi. Thanks for your response. For testing purposes, I created a simple sample project which you can find here:
https://github.com/adelburekovic/AudioPlayerTestExample

When you run this project on a device you will see the error I mentioned in the logs while closing the modal view controller.

Thanks.

**Comment by danielmartinprieto** [comment]
@adelburekovic Thanks for the sample project! I've checked it and I don't think you're doing anything wrong. After some research, I'd say that pausing the player is not a synchronous operation, so we shouldn't be deactivating the session before knowing that the player has been paused (see the response in [this thread](https://forums.developer.apple.com/thread/20435)).

A solution for this problem could be that we listen to changes to [`timeControlStatus`](https://developer.apple.com/documentation/avfoundation/avplayer/1643485-timecontrolstatus) and deactivate the audio session when the player has really been [paused](https://developer.apple.com/documentation/avfoundation/avplayertimecontrolstatus/paused).

What do you think?

cc/ @delannoyk

**Comment by mreil617** [comment]
I'm seeing this same issue. It only happens on my device, not on the simulator. The worst part is that this happens when the player is in a stopped state.

**Comment by adelburekovic** [comment]
The library is stopping the player incorrectly. You'll need to stop the player correctly as described in the comment above by @danielmartinprieto. Sadly I didn't have time to tackle this issue yet.

**Comment by EternalBlack** [comment]
I just ran into that issue too (unfortunately in a production environment as I wasn't expecting something like this to happen).
Works pretty fine in simulator but keeps stopping playback on a real device. Is there a fix available currently? Otherwise I unfortunately need to switch over to another framework for now as I can't risk this happening on the live system. :/

**Comment by mreil617** [comment]
I wasn't able to fix the issue. You have two options though. Make a pull
request other tear it out. I personally recommend using first party libs.
Apple's audio players are great

**Comment by EternalBlack** [comment]
@mreil617 Thank you for the information.

I actually managed to work around it. In my case I had two instances of the AudioPlayer (one for music playback and one for UI loading playback. As `AVAduioSession` is usually shared, they probably interfered with each other. Deleting the UI player solved the issue (playback is back to normal again). I currently just use a simple AVAudioPlayer for UI playback.

**Comment by meshileya** [comment]
@adelburekovic , i tried listening to the state as well using this

if player.timeControlStatus == .paused{
            do{
                try self.session!.setActive(false, options: .notifyOthersOnDeactivation)

            }catch let error {
                print("ERROR==> \(error.localizedDescription)")
            }
        }

but still getting the error, is there anything i could have been doing wrong?

**Comment by lsamaria** [comment]
This is how I did it. Read the 9 steps in the commented out code.

```
var player: AVPlayer?
var wasPlayerPlayingBeforeItWentToTheBackground = false // 0. this is needed in steps 2 and 6 

func checkIfPlayerWasPlayingWhenAppEntersBackground() { // 1. this gets called in the UIApplication.didEnterBackgroundNotification selector method

    if let player = player, player.isPlaying  {
                
        wasPlayerPlayingBeforeItWentToTheBackground = true // 2.  this is needed in step 6

        player.pause() // 3. once the player is paused the `.timeControlStatus` will fire when it's 100% stopped
    }
}

playerTimeControlStatusObserver = player?.observe(\.timeControlStatus, options: [.new, .old]) { [weak self](player, change) in

    switch (player.timeControlStatus) {
        // ... other cases

        case .paused: // 4. read the very long function name to see what happens here
            DispatchQueue.main.async { [weak self] in
                self?.checkTimeStatusAndApplicationStateToMakeSureThePlayerIsDefinitelyStoppedAndInTheBackground()
            }

        // ... other cases
    }
}

func checkTimeStatusAndApplicationStateToMakeSureThePlayerIsDefinitelyStoppedAndInTheBackground() {

    let state = UIApplication.shared.applicationState
    if state == .background { // 5. this code only runs if it's in the background

        if wasPlayerPlayingBeforeItWentToTheBackground { // 6. this has to be true

            wasPlayerPlayingBeforeItWentToTheBackground = false // 7. set it back to false

            do { // 8. deactivate the AVAudioSession
                try AVAudioSession.sharedInstance().setActive(false)
                try AVAudioSession.sharedInstance().setCategory(.playback, mode: .default)
                try AVAudioSession.sharedInstance().setActive(true)
            } catch let err as NSError {
                print(err.localizedDescription)
            }
        }
    }
}

NotificationCenter.default.addObserver(self,
                                               selector: #selector(appDidEnterBackground),
                                               name: UIApplication.didEnterBackgroundNotification, object: nil)

@objc func appDidEnterBackground() {

    checkIfPlayerWasPlayingWhenAppEntersBackground() // 9. when the app is backgrounded run the code from step 1.
}
```
