### ISSUE TITLE
tvOS - AudioPlayer's state doesn't change after loosing connection.

### ISSUE THREAD

**Issue by danielmartinprieto** [delannoyk/AudioPlayer#32]
This issue has been observed in a tvOS app, I don't know if it is the case in iOS too.

While playing an audio item you disable the WiFi to test a reconnect scenario, the player's state doesn't change (is still **Playing**). Therefore, when Reachabilty detects that there is Internet connection again and performs the retrying, the method returns at the beginning, assuming that the audio is still being played.

**Comment by delannoyk** [comment]
Hi Daniel,

That's weird because if the player' state if still `.Playing` when reachability changes to a connected mode, the handler should not do anything:

```
        if state == .WaitingForConnection {
            //Nope
        }
        else if state != .Stopped && state != .Paused {
            if reachability.isReachable() || (currentItem?.soundURLs[currentQuality ?? defaultQuality]?.isOfflineURL ?? false) {
                retryOrPlayNext() //Doesn't do anything since state == .Playing
                connectionLossDate = nil
                stateWhenConnectionLost = nil
            }
            else {
                //Nope
            }
        }
```

So player' state is still `.Playing` but is it still playing audio? (Emptying the buffer)

**Comment by danielmartinprieto** [comment]
Sorry, I explained myself very poorly.

When the connection is lost, eventually the underlaying player stops playing (I'm using an online stream), but somehow the AudioPlayer class doesn't get notified about this, so its state doesn't change either (and therefore is still `.Playing`. Reachability does its work and, when connected back, the `retryOrPlayNext()` method is properly called, but it ends in this line:
https://github.com/delannoyk/AudioPlayer/blob/master/AudioPlayer/AudioPlayer/AudioPlayer.swift#L1071

The audio, though, never comes back.

I'm wondering if there is any bug in the AVPlayer class, or we're not observing all the properties needed to be notified about the player or its items when their state change in all possible scenarios.

**Comment by delannoyk** [comment]
Found the cause. Working on a fix right now :) Should be available in `develop` branch tonight.

**Comment by delannoyk** [comment]
Should be fixed if you use develop. Can you confirm you no longer have the issue? If so, I'll move it to master :)

**Comment by danielmartinprieto** [comment]
That's great! I will test it tonight and give you feedback. Thanks again for putting this together.

**Comment by danielmartinprieto** [comment]
@delannoyk hey, have you push your changes? I can't see them in develop.

**Comment by delannoyk** [comment]
Indeed my bad, sorry about that. Anyway, it's pushed now :P

**Comment by danielmartinprieto** [comment]
@delannoyk sorry, unfortunately this didn't solve the issue. When the connection is lost, the AudioPlayer's state doesn't change (AudioPlayer thinks that it is still playing audio), so the scenario is the same.

Ideally, once the connection is lost, the AudioPlayer's state should pass to a `.WaitingForConnection`. I think after that it will recover from that state properly.

**Comment by delannoyk** [comment]
Oh ok, worked fine on iOS, I'll have a deeper look on tvOS.

Anyway, I don't think going to `.WaitingForConnection` as soon as the connection is lost is a good idea since you might still be playing (buffered audio).

I'll have more time tomorrow to check it out. Thanks for letting me know!

**Comment by danielmartinprieto** [comment]
Yeah, I agree. Maybe if AVPlayer tells us when exactly the buffer is empty, that way we can change the state of the player and be consistent. I work with a live stream, and therefore the sound is stopped very soon after the device has lost Internet connection. I wait for the AudioPlayer's delegate to notify to the change in its state but that never happens, I think that's the main issue so far.

Thanks and let me know if I can be of any help.

**Comment by funkenstrahlen** [comment]
Maybe this is somehow linked to #21?

**Comment by delannoyk** [comment]
Hi guys,
I pushed something to develop that I was able to reproduce constantly on a Icecast live stream. Hopefully it should be the fix for this issue :)
Although I don't think this relates to #21, I'm still investigating that one.
Let me know if this helps you guys.

**Comment by delannoyk** [comment]
Sorry, I meant on master since this is a real bug fix.

**Comment by danielmartinprieto** [comment]
Hi, @delannoyk. I've tested this and it seems to work properly now, congrats!
And thanks! :100:

**Comment by delannoyk** [comment]
Great! I'll close this one then :)
